site_name: "Making data findable"
repo_url: https://github.com/snd-sweden/making-data-findable/
repo_name: making-data-findable
copyright: 'Chalmers University of Technology, KTH Royal Institute of Technology, Swedish National Data Service & University of Gothenburg 2026 | <a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC-BY 4.0</a>'

theme:
    name: material
    language: en
    logo: img/snd.svg
    palette:
        primary: white
        accent: indigo
    features:
        - header.autohide
        - navigation.top
        - navigation.footer
        - navigation.tabs
        - search.suggest
        - search.highlight
        
extra:
    generator: false
    social:
    - icon: fontawesome/solid/house 
      link: https://snd.se
    - icon: fontawesome/brands/github 
      link: https://github.com/snd-sweden
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/2228489365
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@svensknationelldatatjanst8231
      
plugins:
    - search: {}
#    - bibtex:
#        bib_file: "refs.bib"
#        csl_file: "ieee.csl"
#        bib_by_default: true

markdown_extensions:
    - toc:
        permalink: true
        toc_depth: 2
#    - footnotes

nav:
#    - Making data findable: index.md
#    - Recommendations for researchers:
#        - researchers/index.md
#        - 1. Create independent data publications: researchers/core-independent.md
#        - 2. Use PIDs: researchers/core-pids.md
#        - 3. Cite data: researchers/core-cite.md
#    - Recommendations for organisations: 
#        - organisations/index.md
#        - 1. Manage organisational metadata and PIDs: organisations/core-metadata.md
#        - 2. Monitor and curate data: organisations/core-curate.md
#        - 3. Connect and automate: organisations/core-connect.md
    - Making data findable: index.md
    - Recommendations for researchers:
        - researchers/index.md
        - Publication and citation: researchers/publication-citation.md
        - Metadata and identifiers: researchers/metadata-identifiers.md
        - Tools and workflows: researchers/tools-workflows.md 
    - Recommendations for organisations: 
        - organisations/index.md
        - Strategic implementation: organisations/strategic-implementation.md
        - Infrastructure and standards: organisations/infrastructure-standards.md
        - Support and services: organisations/support-services.md